---
- hosts: tag_Name_ec2
  tasks:
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
      become: true
      become_method: sudo

    - shell: hostname
      # become: true
      # become_method: sudo

- hosts: tag_Name_ec2
  tasks:
    - ansible.builtin.script:
        cmd: shell.sh
      become: true
      become_method: sudo
